# Generated by Django 5.0.4 on 2024-11-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
