# Generated by Django 5.0.4 on 2024-11-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_payroll_net_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Стаж работы'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('working', 'Работает'), ('vacation', 'В отпуске'), ('fired', 'Уволен')], default='working', max_length=50, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(verbose_name='Описание отдела'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название отдела'),
        ),
    ]
