# Generated by Django 5.0.4 on 2024-11-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_document_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Работает', 'Работает'), ('В отпуске', 'В отпуске'), ('Уволен', 'Уволен')], default='Работает', max_length=50, verbose_name='Статус'),
        ),
    ]
